(function() {var g,k="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,m={};function n(a,b){(m[a]=m[a]||[]).push(b);var c=k;a=a.split(".");for(var d=0;d<a.length-1&&c;d++)c=c[a[d]];a=a[a.length-1];c&&c[a]instanceof Function&&(c[a]=b(c[a]))}
function p(){p=function(){};if(!k.Symbol){k.Symbol=aa;var a=[],b=function(b){return function(d){a=[];d=b(d);for(var e=[],f=0,h=d.length;f<h;f++){var l;a:if(l=d[f],14>l.length)l=!1;else{for(var v=0;14>v;v++)if(l[v]!="jscomp_symbol_"[v]){l=!1;break a}l=!0}l?a.push(d[f]):e.push(d[f])}return e}};n("Object.keys",b);n("Object.getOwnPropertyNames",b);n("Object.getOwnPropertySymbols",function(c){return function(d){b.Da=Object.getOwnPropertyNames(d);a.push.apply(c(d));return a}})}}var ba=0;
function aa(a){return"jscomp_symbol_"+a+ba++}function q(){p();k.Symbol.iterator||(k.Symbol.iterator=k.Symbol("iterator"));q=function(){}}function r(a){q();p();q();var b=a[Symbol.iterator];if(b)return b.call(a);var c=0;return{next:function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}}function t(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function u(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}var w="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function y(a,b){if(b){for(var c=k,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];b=b(e);if(b!=e){a=m[a]||[];for(e=0;e<a.length;e++)b=a[e](b);w(c,d,{configurable:!0,writable:!0,value:b})}}}
y("WeakMap",function(a){function b(a){this.X=(l+=Math.random()+1).toString();if(a){p();q();a=r(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(a){if(!x(a,f)){var b={};b[f]=h;w(a,f,{value:b})}}function d(a){return function(b){var c=a(b);if(x(b,f)&&x(b[f],f)&&b[f][f]===h)for(b=0;b<c.length;b++)if(c[b]==f){c.splice(b,1);break}return c}}function e(a){return function(b){c(b);return a(b)}}if(function(){if(!a||!Object.seal)return!1;var b=Object.seal({}),c=Object.seal({}),d=new a([[b,
2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}())return a;var f="$jscomp_hidden_"+Math.random().toString().substring(2),h={};n("Object.getOwnPropertyNames",d);n("Object.keys",d);n("Reflect.enumerate",d);n("Reflect.ownKeys",d);n("Object.freeze",e);n("Object.preventExtensions",e);n("Object.seal",e);var l=0;b.prototype.set=function(a,b){c(a);if(!x(a,f))throw Error("WeakMap key fail: "+a);a[f][this.X]=b;return this};b.prototype.get=function(a){return x(a,
f)?a[f][this.X]:void 0};b.prototype.has=function(a){return x(a,f)&&x(a[f],this.X)};b.prototype.delete=function(a){return x(a,f)&&x(a[f],this.X)?delete a[f][this.X]:!1};return b});
y("Map",function(a){function b(){var a={};return a.previous=a.next=a.head=a}function c(a,b){var c=a.H,d={next:function(){if(c){for(;c.head!=a.H;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d}function d(a,b){var c;c=b&&typeof b;"object"==c||"function"==c?f.has(b)?c=f.get(b):(c=""+ ++h,f.set(b,c)):c="p_"+b;var d=a.W[c];if(d&&x(a.W,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||
b===e.key)return{id:c,list:d,index:a,f:e}}return{id:c,list:d,index:-1,f:void 0}}function e(a){this.W={};this.H=b();this.size=0;if(a){a=r(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(r([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();
return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(f){return!1}}())return a;p();q();var f=new WeakMap;e.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.W[c.id]=[]);c.f?c.f.value=b:(c.f={next:this.H,previous:this.H.previous,head:this.H,key:a,value:b},c.list.push(c.f),this.H.previous.next=c.f,this.H.previous=c.f,this.size++);return this};e.prototype.delete=function(a){a=d(this,a);return a.f&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.W[a.id],
a.f.previous.next=a.f.next,a.f.next.previous=a.f.previous,a.f.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.W={};this.H=this.H.previous=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).f};e.prototype.get=function(a){return(a=d(this,a).f)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};
e.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});function ca(a,b){q();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
y("Array.prototype.keys",function(a){return a?a:function(){return ca(this,function(a){return a})}});y("Object.assign",function(a){return a?a:function(a,c){for(var d=1;d<arguments.length;d++){var e=arguments[d];if(e)for(var f in e)x(e,f)&&(a[f]=e[f])}return a}});
y("String.prototype.includes",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(a,c||0)}});
y("Array.prototype.find",function(a){return a?a:function(a,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(a.call(c,h,f,d)){a=h;break a}}a=void 0}return a}});function z(a){this.type=a}z.prototype.required=function(a,b){b=b[a];if(null==b||typeof b!=this.type)throw new TypeError("expected "+this.type+' for property "'+a+'", found: '+JSON.stringify(b));return b};
z.prototype.optional=function(a,b){b=b[a];if(null!=b&&typeof b!=this.type)throw new TypeError("expected optional "+this.type+' for property "'+a+'", found: '+JSON.stringify(b));return b};var A=new z("string"),da=new z("boolean"),ea=new z("number");function fa(a,b){a=b[a];if("string"!==typeof a)throw new TypeError('expected string value in property "experiments", found: '+JSON.stringify(a));return a};function B(){}function C(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];if(!a)throw Error(2>arguments.length?"invalid argument":ga.apply(B,[].concat([b],d instanceof Array?d:t(r(d)))));}function ha(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];if(!a)throw Error(2>arguments.length?"invalid state":ga.apply(B,[].concat([b],d instanceof Array?d:t(r(d)))));}
function ga(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=0;return a.replace(/\{}/g,function(){return e<c.length?c[e++]:"{}"})};function D(a){this.F=a.F;this.G=a.G;this.user=a.user;this.l=a.l;this.w=a.w;this.o=a.o;this.C=a.C;this.u=a.u;this.D=a.D}
function E(a){var b=A.required("experience",a),c;c=a.experiments;if(null!=c){if("object"!==typeof c)throw new TypeError('expected map for property "experiments", found: '+JSON.stringify(c));for(var d=new Map,e=r(Object.keys(c)),f=e.next();!f.done;f=e.next())f=f.value,d.set(f,fa(f,c));c=d}c=c||new Map;var d=A.optional("user",a)||null,e=A.optional("brand",a)||null,f=da.optional("personal",a)||null,h;h=ea.optional("cohort",a);return new D({F:b,G:c,user:d,l:e,w:f,o:h||null,C:A.optional("tier",a)||null,
u:A.optional("countryCode",a)||null,D:A.optional("userLocale",a)||null})};function F(a){this.g=a;this.qa=null;this.ready=!1}function G(a,b){var c=Object.assign({},b),d={};a.qa&&(c.design=a.qa);c.experience=a.g.F;a.g.G.forEach(function(a,b){c["Experiment_"+b]=a;d[b]=a});c.experiments=JSON.stringify(d);a.g.l&&(c.brand=a.g.l);null!=a.g.w&&(c.personal=a.g.w);null!=a.g.o&&(c.cohort=a.g.o);a.g.C&&(c.tier=a.g.C);null!=a.g.u&&(c.country_code=a.g.u);null!=a.g.D&&(c.locale=a.g.D);c.product_variant="web-1";ia(c);return c}
function ia(a){try{var b=window.crypto||window.msCrypto,c=new Uint8Array(16);b.getRandomValues(c);a.insert_id=btoa(String.fromCharCode.apply(null,c))}catch(d){}}
function ja(a,b){var c=window.lastUserTraits||H(new I),d=J(new I,"__user",a);a=a!==c.get("__user");if(b&&K(b)){for(var e=r(b),f=e.next();!f.done;f=e.next()){var h=r(f.value),f=h.next().value,h=h.next().value;a=a||h!==c.get(f)}c=r(b.keys());for(e=c.next();!e.done;e=c.next())e=e.value,J(d,e,b.get(e))}a&&(window.lastUserTraits=H(d));return a}function K(a){C(a instanceof Map,"Could not convert traits to an object; traits value not considered a Map instance");return!0}
F.prototype.zoom=function(a,b,c,d,e){this.track("zoom",{type:a,section:b,subsection:c,location:d,value:e})};function I(){this.items=[]}function J(a,b,c){a.items.push({key:b,value:c});return a}function H(a){return new Map(a.items.map(function(a){return[a.key,a.value]}))};function L(a,b){this.ga=a;this.namespace=void 0===b?null:b}L.prototype.setItem=function(a,b){try{return this.ga.setItem(null==this.namespace?a:this.namespace+"."+a,b),!0}catch(c){return!1}};L.prototype.getItem=function(a){return this.ga.getItem(null==this.namespace?a:this.namespace+"."+a)};L.prototype.removeItem=function(a){this.ga.removeItem(null==this.namespace?a:this.namespace+"."+a)};function M(a){D.call(this,a)}u(M,D);function N(a){F.call(this,a);this.K=null}u(N,F);g=N.prototype;g.track=function(a,b){window.console.log("analytics:track",this.K,a,G(this,b));return P.resolve()};
g.identify=function(a,b,c){this.K=a;if(ja(a,b)){var d=window.lastUserTraits||H(new I),e=J(new I,"__user",a);if(d&&K(d))for(var f=r(d.keys()),h=f.next();!h.done;h=f.next())h=h.value,"__user"!==h&&J(e,h,d.get(h));if(b&&K(b))for(d=r(b.keys()),h=d.next();!h.done;h=d.next())f=h.value,J(e,f,b.get(f));window.lastUserTraits=H(e);window.console.log("analytics:identify",a,b,c)}return P.resolve()};g.alias=function(a){window.console.log("analytics:alias",this.K,a);this.K=a};
g.set=function(a){window.console.log("analytics:set",this.K,a);return P.resolve()};g.union=function(a){window.console.log("analytics:union",this.K,a)};function O(a,b){F.call(this,a);C(1<=b.length,"Requires at least one Analytics client");this.clients=b}u(O,F);g=O.prototype;g.track=function(a,b){return P.all(this.clients.map(function(c){return c.track(a,b)}))};g.identify=function(a,b,c){return P.all(this.clients.map(function(d){return d.identify(a,b,c)}))};g.alias=function(a){this.clients.map(function(b){return b.alias(a)})};g.set=function(a){return P.all(this.clients.map(function(b){return b.set(a)}))};g.union=function(a){this.clients.forEach(function(b){return b.union(a)})};var Q=new ka;function ka(){}g=ka.prototype;g.setInterval=function(a,b){return window.setInterval(a,b)};g.clearInterval=function(a){window.clearInterval(a)};g.setTimeout=function(a,b){return window.setTimeout(a,b)};g.clearTimeout=function(a){window.clearTimeout(a)};g.requestAnimationFrame=function(a){return window.requestAnimationFrame(a)};g.cancelAnimationFrame=function(a){window.cancelAnimationFrame(a)};function R(a){D.call(this,a);this.Z=a.Z;this.ba=a.ba;this.R=a.R}u(R,D);function la(a){var b=E(a);return new R({F:b.F,G:b.G,user:b.user,l:b.l,w:b.w,o:b.o,C:b.C,Z:A.required("segmentJsUrl",a),ba:A.required("segmentWriteKey",a),R:A.required("segmentApiHost",a),u:b.u,D:b.D})};function S(a,b){var c=this;F.call(this,a);this.Z=a.Z;this.ba=a.ba;this.R=a.R;this.va=b;this.ia=null;this.defer(function(){return T(c)})}u(S,F);g=S.prototype;g.track=function(a,b){var c=this;return this.defer(function(d){T(c).track(a,G(c,b),{},function(){return d()})})};g.identify=function(a,b,c){var d=this;return ja(a,b)?this.ia=this.defer(function(e){T(d).identify(a,d.ea(b),c,function(){return e()})}):this.ia||P.resolve()};g.alias=function(a){var b=this;this.defer(function(){T(b).alias(a)})};
g.set=function(a){var b=this;return this.defer(function(c){T(b).identify(b.ea(a),function(){return c()})})};g.union=function(){};g.ea=function(a){var b={};if(a&&K(a)){a=r(a);for(var c=a.next();!c.done;c=a.next()){var d=r(c.value),c=d.next().value,d=d.next().value;b[c]=d}}return b};function ma(){ha("undefined"!==typeof window.analytics,"SegmentAnalytics: window['analytics'] not available");return window.analytics}
function T(a){var b=ma();window.segmentAnalyticsLoaded||(window.segmentAnalyticsLoaded=!0,b.load(a.Z,{"Segment.io":{apiKey:a.ba,apiHost:a.R}}),b.page({path:location.pathname,url:location.href},{}));return b}g.defer=function(a){var b=this;return new P(function(c){b.va.setTimeout(function(){return a(c)},0)})};function U(a){D.call(this,a);this.url=a.url}u(U,D);function na(a){var b=E(a);return new U({F:b.F,G:b.G,user:b.user,l:b.l,w:b.w,o:b.o,C:b.C,url:A.required("sensorsDataUrl",a),u:b.u,D:b.D})};function V(a,b,c){F.call(this,a);this.url=a.url;this.va=b;this.ra=c}u(V,F);
function oa(a,b){b=!(!b||!b.getItem("sensorsDataLoggingEnabled"));window.sensorsDataAnalytic201505="sa";var c={},d={};window.sa=(d.para=(c.name="sa",c.server_url=a.url,c.heatmap={},c.cross_domain=!0,c.show_log=b,c.send_type="ajax",c),d);b=new P(function(a,b){var c=document.createElement("script");c.src="https://static.canva.com/static/lib/sensorsdata-1.14.12.min.js";c.onerror=function(a){return b(a)};c.onload=function(){return a(window.sa)};document.body.appendChild(c)});b.then(function(a){var b=["utm_source","utm_medium",
"utm_term","utm_content","utm_campaign"];window.location.search.substring(1).split("\x26").forEach(function(c){var d=r(c.split("\x3d"));c=d.next().value;d=d.next().value;if(b.includes(c)){var v={};d&&a&&a.Aa&&a.Aa((v["$latest_"+c]=decodeURIComponent(d),v))}})});return new V(a,Q,b)}g=V.prototype;g.track=function(a,b){var c=this;return this.ra.then(function(d){return d.track(a,G(c,b))})};g.identify=function(a,b){var c=this;return this.ra.then(function(d){d.login(a);b&&d.setProfile(c.ea(b))})};
g.alias=function(){};g.set=function(){};g.union=function(){};g.ea=function(a){var b={};if(a&&K(a)){a=r(a);for(var c=a.next();!c.done;c=a.next()){var d=r(c.value),c=d.next().value,d=d.next().value;b[c]=d}}return b};function W(a){D.call(this,a);this.oa=a.oa;this.na=a.na}u(W,D);function X(a,b){ma();if(a instanceof M)b=new N(a);else if(a instanceof R)b=new S(a,Q);else if(a instanceof U)b=oa(a,b);else if(a instanceof W){b=oa(a.oa,b);var c=new S(a.na,Q);b=new O(a,[b,c])}else throw Error("Invalid analytics config");a.user&&b.identify(a.user,null);return b}
function pa(){var a=window.analyticsConfig;if(null==a||"object"!=typeof a)throw new TypeError("expected an object, found: "+a);var b=A.required("impl",a),c=null;try{if(window.localStorage)c=new L(window.localStorage,void 0);else throw Error("ClientStore: localStorage is not defined on window, likely an unsupported browser");}catch(d){}switch(b){case "console":return X(new M(E(a)),c);case "segment":return X(la(a),c);case "sensorsdata":return X(na(a),c);case "sensorsdata-segment-mux":return b=E(a),
a=new W({F:b.F,G:b.G,user:b.user,l:b.l,w:b.w,o:b.o,C:b.C,u:b.u,D:b.D,oa:na(a),na:la(a)}),X(a,c);default:throw Error('No such analytics type: "'+b+'"');}};function qa(a){this.a=[];this.ka=a.ka;this.N=a.N;this.O=a.O;this.v=null;this.ja=a.ja;this.i=a.i}
qa.prototype.Y=function(){var a=this;return new P(function(b,c){a.i.crossOrigin="anonymous";a.i.onload=function(c){c=c.target;a.v={xa:c.width,wa:c.height,ua:c.width/a.N,ta:c.height/a.O,ya:c};for(c=0;c<a.N;c++)for(var e=0;e<a.O;e++)a.a.push(new ra({id:_.uniqueId("PIECE_"),b:c,c:e,ca:c,da:e,model:a}));_.sample(a.a).hidden=!0;c=a.ka;for(var f;c--;){do e=ta(a);while(e[1]===f);ua(e[0],e[1]);f=e[1]}b()};a.i.onerror=c;a.i.src=a.ja})};
function va(a,b){var c;c=c||a.a.filter(function(a){return a.hidden})[0];return wa(a,b.b,b.c,c.b,c.c)&&(b.hidden||c.hidden)?(ua(b,c),[b,c]):!1}function ua(a,b){var c=r([a.b,b.b]);b.b=c.next().value;a.b=c.next().value;c=r([a.c,b.c]);b.c=c.next().value;a.c=c.next().value}
function ta(a){var b=a.a.filter(function(a){return a.hidden})[0],c=[[b.b-1,b.c],[b.b+1,b.c],[b.b,b.c-1],[b.b,b.c+1]],c=c.filter(function(c){return wa(a,b.b,b.c,c[0],c[1])}),d=_.sample(c),c=a.a.filter(function(a){return a.b===d[0]&&a.c===d[1]})[0];return[b,c]}function xa(a){var b=!a.a.some(function(a){return a.ca!==a.b||a.da!==a.c});b&&a.a.filter(function(a){return a.hidden}).forEach(function(a){a.hidden=!1});return b}
function wa(a,b,c,d,e){return(1===Math.abs(b-d)&&0===Math.abs(c-e)||0===Math.abs(b-d)&&1===Math.abs(c-e))&&0<=b&&0<=c&&0<=d&&0<=e&&b<a.N&&c<a.O&&d<a.N&&e<a.O}function ra(a){this.id=a.id;this.ca=a.ca;this.da=a.da;this.b=a.b;this.c=a.c;this.v=a.model.v;this.hidden=!1}
Object.defineProperties(ra.prototype,{height:{configurable:!0,enumerable:!0,get:function(){return this.v.ta}},width:{configurable:!0,enumerable:!0,get:function(){return this.v.ua}},la:{configurable:!0,enumerable:!0,get:function(){return this.b*this.width}},ma:{configurable:!0,enumerable:!0,get:function(){return this.c*this.height}},Ba:{configurable:!0,enumerable:!0,get:function(){return this.ca*this.v.ua}},Ca:{configurable:!0,enumerable:!0,get:function(){return this.da*this.v.ta}}});function Y(a){this.j=a.j;this.ha=a.ha;this.aa=this.J=this.pa=this.fa=null}Y.prototype.Y=function(a){this.j.css("width",a.v.xa);this.j.css("height",a.v.wa);var b=a.v.ya;this.fa=$("\x3ccanvas\x3e")[0];this.fa.width=b.width;this.fa.height=b.height;this.pa=this.fa.getContext("2d");this.pa.drawImage(b,0,0);ya(this,a.a);this.j.on("mousedown",".errorPuzzle__gamePiece",this.za.bind(this))};Y.prototype.remove=function(){this.j.off()};
function ya(a,b){b.forEach(function(b){b=za(a,b);a.j.find(".errorPuzzle__piecesContainer").append(b)})}
function za(a,b){a.J||(a.J=$("\x3ccanvas\x3e")[0],a.J.width=b.width,a.J.height=b.height);var c=a.pa.getImageData(b.Ba,b.Ca,b.width,b.height),d=a.J.getContext("2d");d.putImageData(c,0,0);var e=d.getImageData(0,0,b.width,1);Array.prototype.forEach.call(e.data,function(a,b){return e.data[b]=55+1.5*a});var f=d.getImageData(0,0,1,b.height);Array.prototype.forEach.call(f.data,function(a,b){return f.data[b]=40+1.35*a});var h=d.getImageData(0,b.height-1,b.width,1);Array.prototype.forEach.call(h.data,function(a,
b){return h.data[b]=.8*a});var l=d.getImageData(b.width-1,0,1,b.height);Array.prototype.forEach.call(l.data,function(a,b){return l.data[b]=.85*a});d.putImageData(e,0,0);d.putImageData(f,0,0);d.putImageData(h,0,b.height-1);d.putImageData(l,b.width-1,0);a=a.J.toDataURL("image/jpeg");return $("\x3cimg\x3e").attr("src",a).attr("id",b.id).attr("class","errorPuzzle__gamePiece").attr("draggable",!1).css("left",b.la).css("top",b.ma).toggleClass("errorPuzzle__gamePiece--hidden",b.hidden)}
Y.prototype.za=function(a){this.aa&&this.aa($(a.target).attr("id"))};function Aa(a,b,c){a.j.find('.errorPuzzle__gamePiece[id\x3d"'+b.id+'"]').css("left",b.la).css("top",b.ma);a.j.find('.errorPuzzle__gamePiece[id\x3d"'+c.id+'"]').css("left",c.la).css("top",c.ma)}function Ba(a,b){a=a.j.find('.errorPuzzle__gamePiece[id\x3d"'+b.id+'"]');a.removeClass("errorPuzzle__gamePiece--shake").width();a.toggleClass("errorPuzzle__gamePiece--shake",!0)}
function Ca(a){a.j.find(".errorPuzzle__gamePiece--hidden").removeClass("errorPuzzle__gamePiece--hidden").addClass("errorPuzzle__gamePiece--popIn");a.j.addClass("errorPuzzle__gameElem--solved");a.ha.addClass("errorPuzzle__controls--solved")};/*
Background pattern used in this error puzzle (bgpattern.png) from subtlepatterns.com
*/
function Z(a){this.model=a.model;this.view=a.view}Z.prototype.Y=function(){this.model.Y().then(this.view.Y.bind(this.view,this.model));this.view.aa=this.aa.bind(this)};Z.prototype.aa=function(a){var b=this.model.a.filter(function(b){return b.id===a})[0],c=va(this.model,b);c?(Aa(this.view,c[0],c[1]),xa(this.model)&&Ca(this.view)):Ba(this.view,b)};$(function(){try{pa().track("error_page")}catch(d){}var a=$(".errorPuzzle__gameElem"),b=$(".errorPuzzle__controls"),c=_.sample([{i:"../CART211_media/IMG_fiber.jpg",a:{x:3,y:4}},{i:"../CART211_media/IMG_dragon.jpg",a:{x:3,y:4}},{i:"../CART211_media/IMG_benches.jpg",a:{x:3,y:4}},{i:"../CART211_media/IMG_tunnel.jpg",a:{x:4,y:3}},{i:"../CART211_media/IMG_trash.jpg",a:{x:3,y:4}},{i:"../CART211_media/IMG_floor.jpg",a:{x:4,y:4}}]),c=new qa(_.extend({ka:5},
{ja:c.i,N:c.a.x,O:c.a.y,i:new Image}));(new Z({model:c,view:new Y({j:a,ha:b})})).Y()});})();
